urdf_path: frontend/3d_assets/urdf/openarm_bimanual_copy.urdf
joints:
  default_pose:
    openarm_left_joint1: 0.0
    openarm_left_joint2: -0.8
    openarm_left_joint3: 0.0
    openarm_left_joint4: 1.2
    openarm_left_joint5: 0.0
    openarm_left_joint6: 0.0
    openarm_left_joint7: 0.0
    openarm_right_joint1: 0.0
    openarm_right_joint2: 0.8
    openarm_right_joint3: 0.0
    openarm_right_joint4: 1.2
    openarm_right_joint5: 0.0
    openarm_right_joint6: 0.0
    openarm_right_joint7: 0.0
    openarm_left_finger_joint1: 0.0
    openarm_left_finger_joint2: 0.0
    openarm_right_finger_joint1: 0.0
    openarm_right_finger_joint2: 0.0
end_effectors:
  left: openarm_left_link7
  right: openarm_right_link7
