host: "0.0.0.0"
port: 5200

static_routes:
  - url_prefix: "/assets/urdf/"
    filesystem_path: "frontend/3d_assets/urdf/"
  - url_prefix: "/frontend/"
    filesystem_path: "frontend/"

cors:
  allow_origins: ["*"]
