host: "0.0.0.0"
port: 5200

static_routes:
  - url_prefix: "/assets/urdf/"
    filesystem_path: "webui-monitor/3d_assets/urdf/"
  - url_prefix: "/webui-monitor/"
    filesystem_path: "webui-monitor/"

cors:
  allow_origins: ["*"]
